spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school
    username: tetsafna
    password: tetsafna_dev
  mvc:
    view:
      prefix: /
      suffix: .jsp

server:
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
